language: ruby
rvm:
  - 2.1.2
bundler_args: --without development
env:
  - DB=postgresql
before_script:
  - cp config/database.yml.sample config/database.yml
  - sed -i 's/username: newton/username:/g' config/database.yml
script:
  - bundle exec rake db:create db:migrate db:seed
  - bundle exec rake spec
